### ISSUE TITLE
Sha1 Hashing of File Names

### ISSUE THREAD

**Issue by carsongee** [jazkarta/obsolete-edx-sga#9]
We were wondering why we are hashing the uploaded.  It may at least be convenient for us to keep the original file extension for debugging student uploads, and it is already stored in an anonymized student id folder that makes it somewhat "secure" from hash guessing if the file permission system falls down (which it shouldn't).  I know it can be handy for avoiding "bad" file names, and duplicated file names, but at least would be nice to have the submissions be usable without the DB/platform.

**Comment by chrisrossi** [comment]
It was tied to the abstraction of blob storage.  It eliminated duplicate files, provided a key for look up, and freed the storage mechanism from having to worry about file naming and name collisions.  The files on the filesystem would be opaque, but the fact that there were files on a filesystem was an implementation detail of a single implementation.  This would work for storing in database tables, key/value stores, wherever.  But since we've largely abandoned that abstraction for Django's way of doing things anyway, it's not a big deal to change.
